import AppKit
import ImageCaptureCore
import ImageIO

/// Fetches and caches thumbnails generated by the phone.
final class ThumbnailCache {
    static let shared = ThumbnailCache()

    private let cache: NSCache<NSString, NSImage> = {
        let cache = NSCache<NSString, NSImage>()
        cache.countLimit = 1500
        return cache
    }()

    func cached(for item: MediaItem, maxPixel: Int) -> NSImage? {
        cache.object(forKey: key(item, maxPixel))
    }

    func thumbnail(for item: MediaItem, maxPixel: Int) async -> NSImage? {
        let key = key(item, maxPixel)
        if let image = cache.object(forKey: key) { return image }

        let data: Data? = await withCheckedContinuation { continuation in
            item.file.requestThumbnailData(options: [.imageSourceThumbnailMaxPixelSize: maxPixel]) { data, _ in
                continuation.resume(returning: data)
            }
        }
        guard let data, let image = Self.decode(data, maxPixel: maxPixel) else { return nil }
        cache.setObject(image, forKey: key)
        return image
    }

    private func key(_ item: MediaItem, _ maxPixel: Int) -> NSString {
        "\(item.file.ptpObjectHandle)-\(item.name)-\(maxPixel)" as NSString
    }

    /// Decodes with EXIF orientation applied so portrait shots aren't sideways.
    private static func decode(_ data: Data, maxPixel: Int) -> NSImage? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil) else { return nil }
        let options: [CFString: Any] = [
            kCGImageSourceCreateThumbnailFromImageAlways: true,
            kCGImageSourceCreateThumbnailWithTransform: true,
            kCGImageSourceThumbnailMaxPixelSize: maxPixel,
        ]
        guard let image = CGImageSourceCreateThumbnailAtIndex(source, 0, options as CFDictionary) else { return nil }
        return NSImage(cgImage: image, size: NSSize(width: image.width, height: image.height))
    }
}
